# Generated by Django 5.1.3 on 2024-11-09 22:53

from django.db import migrations
from django.conf import settings
import json


class Migration(migrations.Migration):

    def insert_data(apps, schema_editor):
        Speciality = apps.get_model('video_app', 'Speciality')
        with open(settings.BASE_DIR / 'video_app/migrations/data.json', 'r', encoding='utf-8') as file:
            data = json.load(file)
        for s in data:
            Speciality.objects.create(name=s, vector=data[s]["value"], description=data[s]['description'])

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
