# Generated by Django 5.1.3 on 2024-11-09 15:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cluster',
        ),
        migrations.AlterField(
            model_name='video',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=5, null=True),
        ),
    ]
